Resources:
  ArtTableDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.itemsDataTable} 
      AttributeDefinitions:
        - AttributeName: typeId
          AttributeType: S
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: typeId
          KeyType: HASH
        - AttributeName: itemId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST